version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=meisterwerk
      - DB_PASSWORD=meisterwerk
      - DB_NAME=meisterwerk
      - PORT=8080
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: meisterwerk
      POSTGRES_PASSWORD: meisterwerk
      POSTGRES_DB: meisterwerk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meisterwerk"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 